### ISSUE TITLE
Emit is caught twice on the server side

### ISSUE THREAD

**Issue by daninfpj** [lyondhill/socket.io-ruby-client#5]
Tried my own code and your remote_log example. loadLogs event is fired twice with a single emit.

**Comment by jamhall** [comment]
Any update on this? Experiencing the same issue.

**Comment by FeNiX57** [comment]
Hi,

I got this issue and I found a solution.
It's seem that the handshaking is dead twice:
Once in SocketIO.connect (line 13)

``` ruby
response = RestClient.get "#{uri.scheme}://#{uri.host}:#{uri.port}/socket.io/1/"
```

Then a second time in connect_transport method of Client class:

``` ruby
        @transport = WebSocket.new("#{scheme}://#{@uri.host}:#{@uri.port}/socket.io/1/websocket/#{@session_id}", origin: @uri.to_s)
        @transport.send("1::#{@path}")
```

The line 62:

``` ruby
@transport.send("1::#{@path}")
```

open a second websocket.
I just delete it, and next my code works fine!
